/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from 'ethers'
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from './common'

export declare namespace ILienToken {
  export type DetailsStruct = {
    maxAmount: PromiseOrValue<BigNumberish>
    rate: PromiseOrValue<BigNumberish>
    duration: PromiseOrValue<BigNumberish>
    maxPotentialDebt: PromiseOrValue<BigNumberish>
    liquidationInitialAsk: PromiseOrValue<BigNumberish>
  }

  export type DetailsStructOutput = [
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    maxAmount: BigNumber
    rate: BigNumber
    duration: BigNumber
    maxPotentialDebt: BigNumber
    liquidationInitialAsk: BigNumber
  }

  export type LienStruct = {
    collateralType: PromiseOrValue<BigNumberish>
    token: PromiseOrValue<string>
    vault: PromiseOrValue<string>
    strategyRoot: PromiseOrValue<BytesLike>
    collateralId: PromiseOrValue<BigNumberish>
    details: ILienToken.DetailsStruct
  }

  export type LienStructOutput = [
    number,
    string,
    string,
    string,
    BigNumber,
    ILienToken.DetailsStructOutput
  ] & {
    collateralType: number
    token: string
    vault: string
    strategyRoot: string
    collateralId: BigNumber
    details: ILienToken.DetailsStructOutput
  }

  export type PointStruct = {
    amount: PromiseOrValue<BigNumberish>
    last: PromiseOrValue<BigNumberish>
    end: PromiseOrValue<BigNumberish>
    lienId: PromiseOrValue<BigNumberish>
  }

  export type PointStructOutput = [BigNumber, number, number, BigNumber] & {
    amount: BigNumber
    last: number
    end: number
    lienId: BigNumber
  }

  export type StackStruct = {
    lien: ILienToken.LienStruct
    point: ILienToken.PointStruct
  }

  export type StackStructOutput = [
    ILienToken.LienStructOutput,
    ILienToken.PointStructOutput
  ] & {
    lien: ILienToken.LienStructOutput
    point: ILienToken.PointStructOutput
  }

  export type LienActionEncumberStruct = {
    amount: PromiseOrValue<BigNumberish>
    receiver: PromiseOrValue<string>
    lien: ILienToken.LienStruct
    stack: ILienToken.StackStruct[]
  }

  export type LienActionEncumberStructOutput = [
    BigNumber,
    string,
    ILienToken.LienStructOutput,
    ILienToken.StackStructOutput[]
  ] & {
    amount: BigNumber
    receiver: string
    lien: ILienToken.LienStructOutput
    stack: ILienToken.StackStructOutput[]
  }

  export type LienActionBuyoutStruct = {
    chargeable: PromiseOrValue<boolean>
    position: PromiseOrValue<BigNumberish>
    encumber: ILienToken.LienActionEncumberStruct
  }

  export type LienActionBuyoutStructOutput = [
    boolean,
    number,
    ILienToken.LienActionEncumberStructOutput
  ] & {
    chargeable: boolean
    position: number
    encumber: ILienToken.LienActionEncumberStructOutput
  }

  export type BuyoutLienParamsStruct = {
    lienSlope: PromiseOrValue<BigNumberish>
    lienEnd: PromiseOrValue<BigNumberish>
  }

  export type BuyoutLienParamsStructOutput = [BigNumber, BigNumber] & {
    lienSlope: BigNumber
    lienEnd: BigNumber
  }

  export type FileStruct = {
    what: PromiseOrValue<BigNumberish>
    data: PromiseOrValue<BytesLike>
  }

  export type FileStructOutput = [number, string] & {
    what: number
    data: string
  }
}

export declare namespace ClearingHouse {
  export type AuctionStackStruct = {
    lienId: PromiseOrValue<BigNumberish>
    amountOwed: PromiseOrValue<BigNumberish>
    end: PromiseOrValue<BigNumberish>
  }

  export type AuctionStackStructOutput = [BigNumber, BigNumber, number] & {
    lienId: BigNumber
    amountOwed: BigNumber
    end: number
  }

  export type AuctionDataStruct = {
    startAmount: PromiseOrValue<BigNumberish>
    endAmount: PromiseOrValue<BigNumberish>
    startTime: PromiseOrValue<BigNumberish>
    endTime: PromiseOrValue<BigNumberish>
    liquidator: PromiseOrValue<string>
    token: PromiseOrValue<string>
    stack: ClearingHouse.AuctionStackStruct[]
  }

  export type AuctionDataStructOutput = [
    BigNumber,
    BigNumber,
    number,
    number,
    string,
    string,
    ClearingHouse.AuctionStackStructOutput[]
  ] & {
    startAmount: BigNumber
    endAmount: BigNumber
    startTime: number
    endTime: number
    liquidator: string
    token: string
    stack: ClearingHouse.AuctionStackStructOutput[]
  }
}

export interface LienTokenInterface extends utils.Interface {
  functions: {
    'ASTARIA_ROUTER()': FunctionFragment
    'COLLATERAL_TOKEN()': FunctionFragment
    'approve(address,uint256)': FunctionFragment
    'authority()': FunctionFragment
    'balanceOf(address)': FunctionFragment
    'buyoutLien((bool,uint8,(uint256,address,(uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[])))': FunctionFragment
    'calculateSlope(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))': FunctionFragment
    'createLien((uint256,address,(uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[]))': FunctionFragment
    'file((uint8,bytes))': FunctionFragment
    'getAmountOwingAtLiquidation(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))': FunctionFragment
    'getApproved(uint256)': FunctionFragment
    'getAuctionData(uint256)': FunctionFragment
    'getAuctionLiquidator(uint256)': FunctionFragment
    'getBuyout(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))': FunctionFragment
    'getBuyoutFee(uint256,uint256,uint256)': FunctionFragment
    'getCollateralState(uint256)': FunctionFragment
    'getInterest(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))': FunctionFragment
    'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)': FunctionFragment
    'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[])': FunctionFragment
    'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))': FunctionFragment
    'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)),uint256)': FunctionFragment
    'getPayee(uint256)': FunctionFragment
    'initialize(address,address)': FunctionFragment
    'isApprovedForAll(address,address)': FunctionFragment
    'isValidRefinance((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),uint8,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256,uint256,bool)': FunctionFragment
    'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)': FunctionFragment
    'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint8,uint256)': FunctionFragment
    'name()': FunctionFragment
    'owner()': FunctionFragment
    'ownerOf(uint256)': FunctionFragment
    'payDebtViaClearingHouse(address,uint256,uint256,(uint256,uint256,uint40)[])': FunctionFragment
    'safeTransferFrom(address,address,uint256)': FunctionFragment
    'safeTransferFrom(address,address,uint256,bytes)': FunctionFragment
    'setApprovalForAll(address,bool)': FunctionFragment
    'setAuthority(address)': FunctionFragment
    'stopLiens(uint256,uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],address)': FunctionFragment
    'supportsInterface(bytes4)': FunctionFragment
    'symbol()': FunctionFragment
    'tokenURI(uint256)': FunctionFragment
    'transferFrom(address,address,uint256)': FunctionFragment
    'transferOwnership(address)': FunctionFragment
    'validateLien((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)))': FunctionFragment
  }

  getFunction(
    nameOrSignatureOrTopic:
      | 'ASTARIA_ROUTER'
      | 'COLLATERAL_TOKEN'
      | 'approve'
      | 'authority'
      | 'balanceOf'
      | 'buyoutLien'
      | 'calculateSlope'
      | 'createLien'
      | 'file'
      | 'getAmountOwingAtLiquidation'
      | 'getApproved'
      | 'getAuctionData'
      | 'getAuctionLiquidator'
      | 'getBuyout'
      | 'getBuyoutFee'
      | 'getCollateralState'
      | 'getInterest'
      | 'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'
      | 'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[])'
      | 'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))'
      | 'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)),uint256)'
      | 'getPayee'
      | 'initialize'
      | 'isApprovedForAll'
      | 'isValidRefinance'
      | 'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'
      | 'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint8,uint256)'
      | 'name'
      | 'owner'
      | 'ownerOf'
      | 'payDebtViaClearingHouse'
      | 'safeTransferFrom(address,address,uint256)'
      | 'safeTransferFrom(address,address,uint256,bytes)'
      | 'setApprovalForAll'
      | 'setAuthority'
      | 'stopLiens'
      | 'supportsInterface'
      | 'symbol'
      | 'tokenURI'
      | 'transferFrom'
      | 'transferOwnership'
      | 'validateLien'
  ): FunctionFragment

  encodeFunctionData(
    functionFragment: 'ASTARIA_ROUTER',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'COLLATERAL_TOKEN',
    values?: undefined
  ): string
  encodeFunctionData(
    functionFragment: 'approve',
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(functionFragment: 'authority', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'balanceOf',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'buyoutLien',
    values: [ILienToken.LienActionBuyoutStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'calculateSlope',
    values: [ILienToken.StackStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'createLien',
    values: [ILienToken.LienActionEncumberStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'file',
    values: [ILienToken.FileStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'getAmountOwingAtLiquidation',
    values: [ILienToken.StackStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'getApproved',
    values: [PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'getAuctionData',
    values: [PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'getAuctionLiquidator',
    values: [PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'getBuyout',
    values: [ILienToken.StackStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'getBuyoutFee',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'getCollateralState',
    values: [PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'getInterest',
    values: [ILienToken.StackStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)',
    values: [ILienToken.StackStruct[], PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[])',
    values: [ILienToken.StackStruct[]]
  ): string
  encodeFunctionData(
    functionFragment: 'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))',
    values: [ILienToken.StackStruct]
  ): string
  encodeFunctionData(
    functionFragment: 'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)),uint256)',
    values: [ILienToken.StackStruct, PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'getPayee',
    values: [PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'initialize',
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'isApprovedForAll',
    values: [PromiseOrValue<string>, PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'isValidRefinance',
    values: [
      ILienToken.LienStruct,
      PromiseOrValue<BigNumberish>,
      ILienToken.StackStruct[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)',
    values: [
      PromiseOrValue<BigNumberish>,
      ILienToken.StackStruct[],
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint8,uint256)',
    values: [
      PromiseOrValue<BigNumberish>,
      ILienToken.StackStruct[],
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(functionFragment: 'name', values?: undefined): string
  encodeFunctionData(functionFragment: 'owner', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'ownerOf',
    values: [PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'payDebtViaClearingHouse',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      ClearingHouse.AuctionStackStruct[]
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'safeTransferFrom(address,address,uint256)',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'safeTransferFrom(address,address,uint256,bytes)',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BytesLike>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'setApprovalForAll',
    values: [PromiseOrValue<string>, PromiseOrValue<boolean>]
  ): string
  encodeFunctionData(
    functionFragment: 'setAuthority',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'stopLiens',
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      ILienToken.StackStruct[],
      PromiseOrValue<string>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'supportsInterface',
    values: [PromiseOrValue<BytesLike>]
  ): string
  encodeFunctionData(functionFragment: 'symbol', values?: undefined): string
  encodeFunctionData(
    functionFragment: 'tokenURI',
    values: [PromiseOrValue<BigNumberish>]
  ): string
  encodeFunctionData(
    functionFragment: 'transferFrom',
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BigNumberish>
    ]
  ): string
  encodeFunctionData(
    functionFragment: 'transferOwnership',
    values: [PromiseOrValue<string>]
  ): string
  encodeFunctionData(
    functionFragment: 'validateLien',
    values: [ILienToken.LienStruct]
  ): string

  decodeFunctionResult(
    functionFragment: 'ASTARIA_ROUTER',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'COLLATERAL_TOKEN',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'approve', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'authority', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'buyoutLien', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'calculateSlope',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'createLien', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'file', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'getAmountOwingAtLiquidation',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'getApproved', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'getAuctionData',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getAuctionLiquidator',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'getBuyout', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'getBuyoutFee',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getCollateralState',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'getInterest', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[])',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)),uint256)',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'getPayee', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'isApprovedForAll',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'isValidRefinance',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint8,uint256)',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'ownerOf', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'payDebtViaClearingHouse',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'safeTransferFrom(address,address,uint256)',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'safeTransferFrom(address,address,uint256,bytes)',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setApprovalForAll',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'setAuthority',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'stopLiens', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'supportsInterface',
    data: BytesLike
  ): Result
  decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result
  decodeFunctionResult(functionFragment: 'tokenURI', data: BytesLike): Result
  decodeFunctionResult(
    functionFragment: 'transferFrom',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'transferOwnership',
    data: BytesLike
  ): Result
  decodeFunctionResult(
    functionFragment: 'validateLien',
    data: BytesLike
  ): Result

  events: {
    'AddLien(uint256,uint8,uint8,tuple)': EventFragment
    'Approval(address,address,uint256)': EventFragment
    'ApprovalForAll(address,address,bool)': EventFragment
    'AuthorityUpdated(address,address)': EventFragment
    'BuyoutLien(address,uint256,uint256)': EventFragment
    'FileUpdated(uint8,bytes)': EventFragment
    'Initialized(uint8)': EventFragment
    'OwnershipTransferred(address,address)': EventFragment
    'PayeeChanged(uint256,address)': EventFragment
    'Payment(uint256,uint256)': EventFragment
    'RemoveLien(uint256,uint8)': EventFragment
    'RemovedLiens(uint256)': EventFragment
    'Transfer(address,address,uint256)': EventFragment
  }

  getEvent(nameOrSignatureOrTopic: 'AddLien'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Approval'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'ApprovalForAll'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'AuthorityUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'BuyoutLien'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'FileUpdated'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Initialized'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'PayeeChanged'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Payment'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RemoveLien'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'RemovedLiens'): EventFragment
  getEvent(nameOrSignatureOrTopic: 'Transfer'): EventFragment
}

export interface AddLienEventObject {
  collateralId: BigNumber
  position: number
  stackLength: number
  stack: ILienToken.StackStructOutput
}
export type AddLienEvent = TypedEvent<
  [BigNumber, number, number, ILienToken.StackStructOutput],
  AddLienEventObject
>

export type AddLienEventFilter = TypedEventFilter<AddLienEvent>

export interface ApprovalEventObject {
  owner: string
  spender: string
  id: BigNumber
}
export type ApprovalEvent = TypedEvent<
  [string, string, BigNumber],
  ApprovalEventObject
>

export type ApprovalEventFilter = TypedEventFilter<ApprovalEvent>

export interface ApprovalForAllEventObject {
  owner: string
  operator: string
  approved: boolean
}
export type ApprovalForAllEvent = TypedEvent<
  [string, string, boolean],
  ApprovalForAllEventObject
>

export type ApprovalForAllEventFilter = TypedEventFilter<ApprovalForAllEvent>

export interface AuthorityUpdatedEventObject {
  user: string
  newAuthority: string
}
export type AuthorityUpdatedEvent = TypedEvent<
  [string, string],
  AuthorityUpdatedEventObject
>

export type AuthorityUpdatedEventFilter =
  TypedEventFilter<AuthorityUpdatedEvent>

export interface BuyoutLienEventObject {
  buyer: string
  lienId: BigNumber
  buyout: BigNumber
}
export type BuyoutLienEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  BuyoutLienEventObject
>

export type BuyoutLienEventFilter = TypedEventFilter<BuyoutLienEvent>

export interface FileUpdatedEventObject {
  what: number
  data: string
}
export type FileUpdatedEvent = TypedEvent<
  [number, string],
  FileUpdatedEventObject
>

export type FileUpdatedEventFilter = TypedEventFilter<FileUpdatedEvent>

export interface InitializedEventObject {
  version: number
}
export type InitializedEvent = TypedEvent<[number], InitializedEventObject>

export type InitializedEventFilter = TypedEventFilter<InitializedEvent>

export interface OwnershipTransferredEventObject {
  user: string
  newOwner: string
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>

export interface PayeeChangedEventObject {
  lienId: BigNumber
  payee: string
}
export type PayeeChangedEvent = TypedEvent<
  [BigNumber, string],
  PayeeChangedEventObject
>

export type PayeeChangedEventFilter = TypedEventFilter<PayeeChangedEvent>

export interface PaymentEventObject {
  lienId: BigNumber
  amount: BigNumber
}
export type PaymentEvent = TypedEvent<
  [BigNumber, BigNumber],
  PaymentEventObject
>

export type PaymentEventFilter = TypedEventFilter<PaymentEvent>

export interface RemoveLienEventObject {
  collateralId: BigNumber
  position: number
}
export type RemoveLienEvent = TypedEvent<
  [BigNumber, number],
  RemoveLienEventObject
>

export type RemoveLienEventFilter = TypedEventFilter<RemoveLienEvent>

export interface RemovedLiensEventObject {
  collateralId: BigNumber
}
export type RemovedLiensEvent = TypedEvent<[BigNumber], RemovedLiensEventObject>

export type RemovedLiensEventFilter = TypedEventFilter<RemovedLiensEvent>

export interface TransferEventObject {
  from: string
  to: string
  id: BigNumber
}
export type TransferEvent = TypedEvent<
  [string, string, BigNumber],
  TransferEventObject
>

export type TransferEventFilter = TypedEventFilter<TransferEvent>

export interface LienToken extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this
  attach(addressOrName: string): this
  deployed(): Promise<this>

  interface: LienTokenInterface

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>
  listeners(eventName?: string): Array<Listener>
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this
  removeAllListeners(eventName?: string): this
  off: OnEvent<this>
  on: OnEvent<this>
  once: OnEvent<this>
  removeListener: OnEvent<this>

  functions: {
    ASTARIA_ROUTER(overrides?: CallOverrides): Promise<[string]>

    COLLATERAL_TOKEN(overrides?: CallOverrides): Promise<[string]>

    approve(
      spender: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    authority(overrides?: CallOverrides): Promise<[string]>

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    buyoutLien(
      params: ILienToken.LienActionBuyoutStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    calculateSlope(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    createLien(
      params: ILienToken.LienActionEncumberStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    file(
      incoming: ILienToken.FileStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    getAmountOwingAtLiquidation(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    getApproved(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>

    getAuctionData(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[ClearingHouse.AuctionDataStructOutput]>

    getAuctionLiquidator(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { liquidator: string }>

    getBuyout(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { owed: BigNumber; buyout: BigNumber }>

    getBuyoutFee(
      remainingInterestIn: PromiseOrValue<BigNumberish>,
      end: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { fee: BigNumber }>

    getCollateralState(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>

    getInterest(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'(
      stack: ILienToken.StackStruct[],
      end: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { maxPotentialDebt: BigNumber }>

    'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[])'(
      stack: ILienToken.StackStruct[],
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { maxPotentialDebt: BigNumber }>

    'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))'(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)),uint256)'(
      stack: ILienToken.StackStruct,
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>

    getPayee(
      lienId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>

    initialize(
      _AUTHORITY: PromiseOrValue<string>,
      _TRANSFER_PROXY: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    isValidRefinance(
      newLien: ILienToken.LienStruct,
      position: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      owed: PromiseOrValue<BigNumberish>,
      buyout: PromiseOrValue<BigNumberish>,
      chargeable: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'(
      collateralId: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint8,uint256)'(
      collateralId: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      position: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    name(overrides?: CallOverrides): Promise<[string]>

    owner(overrides?: CallOverrides): Promise<[string]>

    ownerOf(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string] & { owner: string }>

    payDebtViaClearingHouse(
      token: PromiseOrValue<string>,
      collateralId: PromiseOrValue<BigNumberish>,
      payment: PromiseOrValue<BigNumberish>,
      auctionStack: ClearingHouse.AuctionStackStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    'safeTransferFrom(address,address,uint256)'(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    setAuthority(
      newAuthority: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    stopLiens(
      collateralId: PromiseOrValue<BigNumberish>,
      auctionWindow: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<[boolean]>

    symbol(overrides?: CallOverrides): Promise<[string]>

    tokenURI(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string]>

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    validateLien(
      lien: ILienToken.LienStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber] & { lienId: BigNumber }>
  }

  ASTARIA_ROUTER(overrides?: CallOverrides): Promise<string>

  COLLATERAL_TOKEN(overrides?: CallOverrides): Promise<string>

  approve(
    spender: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  authority(overrides?: CallOverrides): Promise<string>

  balanceOf(
    owner: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  buyoutLien(
    params: ILienToken.LienActionBuyoutStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  calculateSlope(
    stack: ILienToken.StackStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  createLien(
    params: ILienToken.LienActionEncumberStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  file(
    incoming: ILienToken.FileStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  getAmountOwingAtLiquidation(
    stack: ILienToken.StackStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  getApproved(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>

  getAuctionData(
    collateralId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<ClearingHouse.AuctionDataStructOutput>

  getAuctionLiquidator(
    collateralId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>

  getBuyout(
    stack: ILienToken.StackStruct,
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber] & { owed: BigNumber; buyout: BigNumber }>

  getBuyoutFee(
    remainingInterestIn: PromiseOrValue<BigNumberish>,
    end: PromiseOrValue<BigNumberish>,
    duration: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  getCollateralState(
    collateralId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>

  getInterest(
    stack: ILienToken.StackStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'(
    stack: ILienToken.StackStruct[],
    end: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[])'(
    stack: ILienToken.StackStruct[],
    overrides?: CallOverrides
  ): Promise<BigNumber>

  'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))'(
    stack: ILienToken.StackStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)),uint256)'(
    stack: ILienToken.StackStruct,
    timestamp: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  getPayee(
    lienId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>

  initialize(
    _AUTHORITY: PromiseOrValue<string>,
    _TRANSFER_PROXY: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  isApprovedForAll(
    owner: PromiseOrValue<string>,
    operator: PromiseOrValue<string>,
    overrides?: CallOverrides
  ): Promise<boolean>

  isValidRefinance(
    newLien: ILienToken.LienStruct,
    position: PromiseOrValue<BigNumberish>,
    stack: ILienToken.StackStruct[],
    owed: PromiseOrValue<BigNumberish>,
    buyout: PromiseOrValue<BigNumberish>,
    chargeable: PromiseOrValue<boolean>,
    overrides?: CallOverrides
  ): Promise<boolean>

  'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'(
    collateralId: PromiseOrValue<BigNumberish>,
    stack: ILienToken.StackStruct[],
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint8,uint256)'(
    collateralId: PromiseOrValue<BigNumberish>,
    stack: ILienToken.StackStruct[],
    position: PromiseOrValue<BigNumberish>,
    amount: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  name(overrides?: CallOverrides): Promise<string>

  owner(overrides?: CallOverrides): Promise<string>

  ownerOf(
    id: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>

  payDebtViaClearingHouse(
    token: PromiseOrValue<string>,
    collateralId: PromiseOrValue<BigNumberish>,
    payment: PromiseOrValue<BigNumberish>,
    auctionStack: ClearingHouse.AuctionStackStruct[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  'safeTransferFrom(address,address,uint256)'(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  'safeTransferFrom(address,address,uint256,bytes)'(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    data: PromiseOrValue<BytesLike>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setApprovalForAll(
    operator: PromiseOrValue<string>,
    approved: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  setAuthority(
    newAuthority: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  stopLiens(
    collateralId: PromiseOrValue<BigNumberish>,
    auctionWindow: PromiseOrValue<BigNumberish>,
    stack: ILienToken.StackStruct[],
    liquidator: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  supportsInterface(
    interfaceId: PromiseOrValue<BytesLike>,
    overrides?: CallOverrides
  ): Promise<boolean>

  symbol(overrides?: CallOverrides): Promise<string>

  tokenURI(
    tokenId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string>

  transferFrom(
    from: PromiseOrValue<string>,
    to: PromiseOrValue<string>,
    id: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>

  validateLien(
    lien: ILienToken.LienStruct,
    overrides?: CallOverrides
  ): Promise<BigNumber>

  callStatic: {
    ASTARIA_ROUTER(overrides?: CallOverrides): Promise<string>

    COLLATERAL_TOKEN(overrides?: CallOverrides): Promise<string>

    approve(
      spender: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>

    authority(overrides?: CallOverrides): Promise<string>

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    buyoutLien(
      params: ILienToken.LienActionBuyoutStruct,
      overrides?: CallOverrides
    ): Promise<
      [
        ILienToken.StackStructOutput[],
        ILienToken.StackStructOutput,
        ILienToken.BuyoutLienParamsStructOutput
      ] & {
        stacks: ILienToken.StackStructOutput[]
        newStack: ILienToken.StackStructOutput
        buyoutParams: ILienToken.BuyoutLienParamsStructOutput
      }
    >

    calculateSlope(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    createLien(
      params: ILienToken.LienActionEncumberStruct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, ILienToken.StackStructOutput[], BigNumber] & {
        lienId: BigNumber
        newStack: ILienToken.StackStructOutput[]
        lienSlope: BigNumber
      }
    >

    file(
      incoming: ILienToken.FileStruct,
      overrides?: CallOverrides
    ): Promise<void>

    getAmountOwingAtLiquidation(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getApproved(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>

    getAuctionData(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ClearingHouse.AuctionDataStructOutput>

    getAuctionLiquidator(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>

    getBuyout(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber] & { owed: BigNumber; buyout: BigNumber }>

    getBuyoutFee(
      remainingInterestIn: PromiseOrValue<BigNumberish>,
      end: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getCollateralState(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>

    getInterest(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'(
      stack: ILienToken.StackStruct[],
      end: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[])'(
      stack: ILienToken.StackStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))'(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)),uint256)'(
      stack: ILienToken.StackStruct,
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getPayee(
      lienId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>

    initialize(
      _AUTHORITY: PromiseOrValue<string>,
      _TRANSFER_PROXY: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<boolean>

    isValidRefinance(
      newLien: ILienToken.LienStruct,
      position: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      owed: PromiseOrValue<BigNumberish>,
      buyout: PromiseOrValue<BigNumberish>,
      chargeable: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<boolean>

    'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'(
      collateralId: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ILienToken.StackStructOutput[]>

    'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint8,uint256)'(
      collateralId: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      position: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<ILienToken.StackStructOutput[]>

    name(overrides?: CallOverrides): Promise<string>

    owner(overrides?: CallOverrides): Promise<string>

    ownerOf(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>

    payDebtViaClearingHouse(
      token: PromiseOrValue<string>,
      collateralId: PromiseOrValue<BigNumberish>,
      payment: PromiseOrValue<BigNumberish>,
      auctionStack: ClearingHouse.AuctionStackStruct[],
      overrides?: CallOverrides
    ): Promise<void>

    'safeTransferFrom(address,address,uint256)'(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<void>

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>

    setAuthority(
      newAuthority: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    stopLiens(
      collateralId: PromiseOrValue<BigNumberish>,
      auctionWindow: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      liquidator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<boolean>

    symbol(overrides?: CallOverrides): Promise<string>

    tokenURI(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string>

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>

    validateLien(
      lien: ILienToken.LienStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>
  }

  filters: {
    'AddLien(uint256,uint8,uint8,tuple)'(
      collateralId?: PromiseOrValue<BigNumberish> | null,
      position?: null,
      stackLength?: null,
      stack?: null
    ): AddLienEventFilter
    AddLien(
      collateralId?: PromiseOrValue<BigNumberish> | null,
      position?: null,
      stackLength?: null,
      stack?: null
    ): AddLienEventFilter

    'Approval(address,address,uint256)'(
      owner?: PromiseOrValue<string> | null,
      spender?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null
    ): ApprovalEventFilter
    Approval(
      owner?: PromiseOrValue<string> | null,
      spender?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null
    ): ApprovalEventFilter

    'ApprovalForAll(address,address,bool)'(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter
    ApprovalForAll(
      owner?: PromiseOrValue<string> | null,
      operator?: PromiseOrValue<string> | null,
      approved?: null
    ): ApprovalForAllEventFilter

    'AuthorityUpdated(address,address)'(
      user?: PromiseOrValue<string> | null,
      newAuthority?: PromiseOrValue<string> | null
    ): AuthorityUpdatedEventFilter
    AuthorityUpdated(
      user?: PromiseOrValue<string> | null,
      newAuthority?: PromiseOrValue<string> | null
    ): AuthorityUpdatedEventFilter

    'BuyoutLien(address,uint256,uint256)'(
      buyer?: PromiseOrValue<string> | null,
      lienId?: null,
      buyout?: null
    ): BuyoutLienEventFilter
    BuyoutLien(
      buyer?: PromiseOrValue<string> | null,
      lienId?: null,
      buyout?: null
    ): BuyoutLienEventFilter

    'FileUpdated(uint8,bytes)'(what?: null, data?: null): FileUpdatedEventFilter
    FileUpdated(what?: null, data?: null): FileUpdatedEventFilter

    'Initialized(uint8)'(version?: null): InitializedEventFilter
    Initialized(version?: null): InitializedEventFilter

    'OwnershipTransferred(address,address)'(
      user?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter
    OwnershipTransferred(
      user?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter

    'PayeeChanged(uint256,address)'(
      lienId?: PromiseOrValue<BigNumberish> | null,
      payee?: PromiseOrValue<string> | null
    ): PayeeChangedEventFilter
    PayeeChanged(
      lienId?: PromiseOrValue<BigNumberish> | null,
      payee?: PromiseOrValue<string> | null
    ): PayeeChangedEventFilter

    'Payment(uint256,uint256)'(
      lienId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): PaymentEventFilter
    Payment(
      lienId?: PromiseOrValue<BigNumberish> | null,
      amount?: null
    ): PaymentEventFilter

    'RemoveLien(uint256,uint8)'(
      collateralId?: PromiseOrValue<BigNumberish> | null,
      position?: null
    ): RemoveLienEventFilter
    RemoveLien(
      collateralId?: PromiseOrValue<BigNumberish> | null,
      position?: null
    ): RemoveLienEventFilter

    'RemovedLiens(uint256)'(
      collateralId?: PromiseOrValue<BigNumberish> | null
    ): RemovedLiensEventFilter
    RemovedLiens(
      collateralId?: PromiseOrValue<BigNumberish> | null
    ): RemovedLiensEventFilter

    'Transfer(address,address,uint256)'(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter
    Transfer(
      from?: PromiseOrValue<string> | null,
      to?: PromiseOrValue<string> | null,
      id?: PromiseOrValue<BigNumberish> | null
    ): TransferEventFilter
  }

  estimateGas: {
    ASTARIA_ROUTER(overrides?: CallOverrides): Promise<BigNumber>

    COLLATERAL_TOKEN(overrides?: CallOverrides): Promise<BigNumber>

    approve(
      spender: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    authority(overrides?: CallOverrides): Promise<BigNumber>

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    buyoutLien(
      params: ILienToken.LienActionBuyoutStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    calculateSlope(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    createLien(
      params: ILienToken.LienActionEncumberStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    file(
      incoming: ILienToken.FileStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    getAmountOwingAtLiquidation(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getApproved(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getAuctionData(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getAuctionLiquidator(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getBuyout(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getBuyoutFee(
      remainingInterestIn: PromiseOrValue<BigNumberish>,
      end: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getCollateralState(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getInterest(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'(
      stack: ILienToken.StackStruct[],
      end: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[])'(
      stack: ILienToken.StackStruct[],
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))'(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)),uint256)'(
      stack: ILienToken.StackStruct,
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    getPayee(
      lienId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    initialize(
      _AUTHORITY: PromiseOrValue<string>,
      _TRANSFER_PROXY: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    isValidRefinance(
      newLien: ILienToken.LienStruct,
      position: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      owed: PromiseOrValue<BigNumberish>,
      buyout: PromiseOrValue<BigNumberish>,
      chargeable: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'(
      collateralId: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint8,uint256)'(
      collateralId: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      position: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    name(overrides?: CallOverrides): Promise<BigNumber>

    owner(overrides?: CallOverrides): Promise<BigNumber>

    ownerOf(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    payDebtViaClearingHouse(
      token: PromiseOrValue<string>,
      collateralId: PromiseOrValue<BigNumberish>,
      payment: PromiseOrValue<BigNumberish>,
      auctionStack: ClearingHouse.AuctionStackStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    'safeTransferFrom(address,address,uint256)'(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    setAuthority(
      newAuthority: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    stopLiens(
      collateralId: PromiseOrValue<BigNumberish>,
      auctionWindow: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    symbol(overrides?: CallOverrides): Promise<BigNumber>

    tokenURI(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>

    validateLien(
      lien: ILienToken.LienStruct,
      overrides?: CallOverrides
    ): Promise<BigNumber>
  }

  populateTransaction: {
    ASTARIA_ROUTER(overrides?: CallOverrides): Promise<PopulatedTransaction>

    COLLATERAL_TOKEN(overrides?: CallOverrides): Promise<PopulatedTransaction>

    approve(
      spender: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    authority(overrides?: CallOverrides): Promise<PopulatedTransaction>

    balanceOf(
      owner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    buyoutLien(
      params: ILienToken.LienActionBuyoutStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    calculateSlope(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    createLien(
      params: ILienToken.LienActionEncumberStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    file(
      incoming: ILienToken.FileStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    getAmountOwingAtLiquidation(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getApproved(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getAuctionData(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getAuctionLiquidator(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getBuyout(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getBuyoutFee(
      remainingInterestIn: PromiseOrValue<BigNumberish>,
      end: PromiseOrValue<BigNumberish>,
      duration: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getCollateralState(
      collateralId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getInterest(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'(
      stack: ILienToken.StackStruct[],
      end: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'getMaxPotentialDebtForCollateral(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[])'(
      stack: ILienToken.StackStruct[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)))'(
      stack: ILienToken.StackStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'getOwed(((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256)),uint256)'(
      stack: ILienToken.StackStruct,
      timestamp: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    getPayee(
      lienId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    initialize(
      _AUTHORITY: PromiseOrValue<string>,
      _TRANSFER_PROXY: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    isApprovedForAll(
      owner: PromiseOrValue<string>,
      operator: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    isValidRefinance(
      newLien: ILienToken.LienStruct,
      position: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      owed: PromiseOrValue<BigNumberish>,
      buyout: PromiseOrValue<BigNumberish>,
      chargeable: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint256)'(
      collateralId: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    'makePayment(uint256,((uint8,address,address,bytes32,uint256,(uint256,uint256,uint256,uint256,uint256)),(uint256,uint40,uint40,uint256))[],uint8,uint256)'(
      collateralId: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      position: PromiseOrValue<BigNumberish>,
      amount: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    name(overrides?: CallOverrides): Promise<PopulatedTransaction>

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

    ownerOf(
      id: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    payDebtViaClearingHouse(
      token: PromiseOrValue<string>,
      collateralId: PromiseOrValue<BigNumberish>,
      payment: PromiseOrValue<BigNumberish>,
      auctionStack: ClearingHouse.AuctionStackStruct[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    'safeTransferFrom(address,address,uint256)'(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      data: PromiseOrValue<BytesLike>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setApprovalForAll(
      operator: PromiseOrValue<string>,
      approved: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    setAuthority(
      newAuthority: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    stopLiens(
      collateralId: PromiseOrValue<BigNumberish>,
      auctionWindow: PromiseOrValue<BigNumberish>,
      stack: ILienToken.StackStruct[],
      liquidator: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    supportsInterface(
      interfaceId: PromiseOrValue<BytesLike>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>

    tokenURI(
      tokenId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>

    transferFrom(
      from: PromiseOrValue<string>,
      to: PromiseOrValue<string>,
      id: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>

    validateLien(
      lien: ILienToken.LienStruct,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>
  }
}
