name: Build

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --frozen-lockfile --no-progress --prefer-offline

      - name: Build
        run: yarn build
