name: Test

on:
  pull_request:
    branches:
      - '**'

permissions:
  checks: write
  contents: write

jobs:
  build:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['18.x', '20.x']
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable --frozen-lockfile --no-progress --prefer-offline

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2
        env:
          NODE_OPTIONS: "${{ matrix.node != '16.x' && '--openssl-legacy-provider' || '' }}"
